version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "5069:3060"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"